### ISSUE TITLE
What License is used for this Project ? 

### ISSUE THREAD

**Issue by Thore-Krug** [KoljaWindeler/CHIP_ZIFFY#2]
Hi, 

I am interested in creating my own C.H.I.P DIP and to save time and effort i would like to use the TZATZIFFY as a basis. 
But i havent found a License File thus i am asking under which LIcense this Project is released.

**Comment by KoljaWindeler** [comment]
Go ahead, use it in what ever way you want. It's all yours

**Comment by Thore-Krug** [comment]
Ok Thanks :)
